### ISSUE TITLE
BUG: Path to Explosion not found

### ISSUE THREAD

**Issue by tup31163** [cis3296s24/Asteroids-Plus#89]
Here is the print out from my terminal. I couldn't find the file paths in the main branch either. 
```
FileNotFoundError: No file 'Images/Explosions/explosions-a1.png' found in working directory 'C:\Users\Kenny Miller\Desktop\Asteroids-Plus'.
```

Running `python Menu.py` with Python 3.12.2 in PowerShell. I commented the paths out and everything is running fine. Looking forward to seeing the Explosion feature.

**Comment by XJ114514** [comment]
I have the same issue.

**Comment by Jericho-R-Orienza** [comment]
Thank you for your report, the issue has been resolved :)
